name: helldivershangar

services:
  helldivershangar-database:
    container_name: helldivershangar-database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: ${TZ}
      PGTZ: ${TZ}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  helldivershangar-api:
    container_name: helldivershangar-api
    image: helldivershangar-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - helldivershangar-database
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  helldivershangar-database-backup:
#    container_name: hdl-database-backup
#    image: prodrigestivill/postgres-backup-local
#    restart: always
#    #       user: postgres:postgres # Optional: see below
#    volumes:
#      - ${DB_BACKUP_LOCATION}:/backups
#    links:
#      - helldivershangar-database
#    depends_on:
#      - helldivershangar-database
#    env_file:
#      - .env
#    environment:
#      - POSTGRES_HOST=hdl-database
#      - POSTGRES_DB=${DB_NAME}
#      - POSTGRES_USER=${DB_USERNAME}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
#      - SCHEDULE=@daily
#      - BACKUP_ON_START=TRUE
#      - BACKUP_KEEP_DAYS=7
#      - BACKUP_KEEP_WEEKS=4
#      - BACKUP_KEEP_MONTHS=6
#      - HEALTHCHECK_PORT=8080
#      - TZ=${TZ}