INSERT INTO public.passive VALUES (1, 'Advanced Filtration', 'Provides 80% resistance to gas damage and effects.'),
(2, 'Med-Kit', 'Increases initial inventory and holding capacity of stims by +2.
Increases stim effect duration by 2.0s.'),
(3, 'Scout', 'Markers placed on the map will generate radar scans every 2.0s.
Reduces range at which enemies can detect the wearer by 30%.'),
(4, 'Standard Issue', 'No additional bonuses.'),
(5, 'Peak Physique', 'Increased Melee Damage by 50%.
Improves weapons handling with less drag on the weapon movement.'),
(6, 'Servo-Assisted', 'Increases throwing range by 30%.
Provides +50% limb health.'),
(7, 'Extra Padding', 'Provides a higher armor rating.'),
(8, 'Engineering Kit', 'Further Reduces recoil when crouching or prone by 30%.
Increases initial inventory and holding capacity of grenades by +2.'),
(9, 'Democracy Protects', '50% chance to not die when taking lethal damage.
Prevents all damage from bleeding if chest hemorrhages.'),
(10, 'Inflammable', 'Provides 75% damage resistance to fire, allowing bearer to rest assured in the inflammability.'),
(11, 'Fortified', 'Further reduces recoil when crouching or prone by 30%.
Provides 50% resistance to explosive damage.'),
(12, 'Electrical Conduit', 'Provides 95% resistance to arc damage.'),
(13, 'Unflinching', 'Helps prevent Helldivers from flinching when hit.');

INSERT INTO public.firing_mode VALUES (1, 'Bolt-Action'),
(2, 'All Barrels'), (3, 'Pump Action'),
(4, 'Automatic'), (5, 'Semi Automatic'),
(6, 'Burst'), (7, 'Charge With Safety On');

INSERT INTO public.trait VALUES (1, 'Medium Armor Penetrating'),
(2, 'Rounds Reload'), (3, 'Heavy Armor Penetrating'),
(4, 'Beam'), (5, 'Explosive'),
(6, 'Light Armor Penetrating'), (7, 'Chargeup'),
(8, 'Incendiary'), (9, 'One Handed'),
(10, 'Stimulative'),(11, 'Heat');

INSERT INTO public.gear VALUES (1, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 500, 100, NULL, 'armor'),
(2, 'B-08 Light Gunner', 'Compact and flexible, this kevlar armor adds minimal mass, making it a common choice for Helldiver fitness tests.', 'Medium', 100, 550, 125, NULL, 'armor'),
(3, 'B-24 Enforcer', 'In field tests, 84% of users said that the armor improved their posture and self-esteem.', 'Medium', 100, 471, 71, NULL, 'armor'),
(4, 'B-27 Fortified Commando', 'This armor set first appeared in the music video for the summer anthem ''Our Love is Like Liberty (Indestructible)''.', 'Heavy', 200, 450, 50, NULL, 'armor'),
(5, 'CE-07 Demolition Specialist', 'Originally worn by lunar terraformers, this suit can withstand rapid changes in pressure, heat, and personal velocity.', 'Light', 64, 536, 118, NULL, 'armor'),
(6, 'CE-27 Ground Breaker', '''The ground is just another obstacle that hasn''t yet been cleared.'' - SGM Janet Jones, Excavation Corps Founder.', 'Medium', 100, 500, 100, NULL, 'armor'),
(7, 'CE-35 Trench Engineer', 'After colonists of Hellmire recovered a lost shipment of this armor, the local pastime of fence-smashing was born.', 'Medium', 100, 500, 100, NULL, 'armor'),
(8, 'CE-64 Grenadier', 'The set''s classic advertising campaign ''Have you tried a grenade?'' has remained unchanged for over 70 years', 'Heavy', 150, 450, 50, NULL, 'armor'),
(9, 'CE-67 Titan', 'A quality product, this armor can destroy over 300,000 kilometers of fencing with no decline in operational efficiency.', 'Light', 79, 521, 111, NULL, 'armor'),
(10, 'CE-74 Breaker', 'A domestic version of this armor is available for citizens who wish to perform efficient home renovation projects.', 'Light', 50, 550, 125, NULL, 'armor'),
(11, 'CE-81 Juggernaut', 'One of the most durable engineer armors available, each set is quality tested by an impact with a full-grown Charger.', 'Medium', 100, 500, 100, NULL, 'armor'),
(12, 'CM-06 Combat Medic', 'This armor was designed by PFC Rodney A. Carmichael, the first Helldiver to use a stim on an ally instead of himself.', 'Medium', 100, 500, 100, NULL, 'armor'),
(13, 'CM-09 Bonesnapper', 'Based on a colonial surgeon''s gown, where surgeries were often interrupted by a need to perform defensive duties.', 'Medium', 100, 500, 100, NULL, 'armor'),
(28, 'EX-16 Prototype 16', 'As the electric arc generates a strong magnetic field, wearers should avoid use while in the vicinity of stapled paperwork', 'Medium', 100, 500, 100, NULL, 'armor'),
(29, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 450, 50, NULL, 'armor'),
(30, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes', 'Heavy', 150, 450, 50, NULL, 'armor'),
(31, 'FS-11 Executioner', 'Popularized by actor Chip Messiter, who wore this in the action-rom-com-musical ''Lost My Heart to a Man in a Helmet.''', 'Medium', 100, 450, 50, NULL, 'armor'),
(32, 'FS-23 Battle Master', 'This aim-stabilizing armor found surprising secondary market success among alien birdwatching enthusiasts.', 'Medium', 100, 450, 50, NULL, 'armor'),
(33, 'FS-23 Battle Master', 'This aim-stabilizing armor found surprising secondary market success among alien birdwatching enthusiasts.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(14, 'CM-10 Clinician', 'Featuring patented reverse-seam technology, to reduce the likelihood of bodily fluids entering the armor''s interior.', 'Medium', 100, 500, 100, NULL, 'armor'),
(15, 'CM-14 Physician', 'The distinctive red, white, and green of the Intergalactic Medical Corps signal to all Helldivers that help is at hand.', 'Medium', 100, 500, 100, NULL, 'armor'),
(16, 'CM-17 Butcher', 'An armor often worn by frontline surgeons, who are skilled at both putting bodies back together and taking them apart.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(17, 'CM-21 Trench Paramedic', 'The suit was once designed to hold a variety of battlefield medical equipment. Now it holds a generous supply of stims.', 'Light', 64, 536, 118, NULL, 'armor'),
(18, 'CW-22 Kodiak', 'The CW-22 Kodiak armor was thoroughly pressure-tested by patriotic volunteers, as part of the ''Test Subjects for Super-Earth'' Citizen Advancement Program.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(19, 'CW-36 Winter Warrior', 'Offering camouflage in snowy environments, surplus sets of this armor are used by nature photographers and keen hunters alike.', 'Medium', 100, 450, 50, NULL, 'armor'),
(20, 'CW-36 Winter Warrior', 'Offering camouflage in snowy environments, surplus sets of this armor are used by nature photographers and keen hunters alike.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(21, 'CW-4 Arctic Ranger', 'Features a utility belt with pockets that can be filled with any number of things, such as pocket knives, mementos from home, and interesting rocks.', 'Light', 50, 550, 125, NULL, 'armor'),
(22, 'CW-9 White Wolf', 'The pattern used for this armor is the result of the Winter Camouflage Improvement Effort, which considered 136 entrants before determining the color white would best blend in with snow.', 'Heavy', 150, 500, 100, NULL, 'armor'),
(23, 'DP-11 Champion of the People', 'The three stripes on the pauldrons stand for the three principles of Super Earth: Liberty, Democracy, and Prosperity.', 'Medium', 100, 500, 100, NULL, 'armor'),
(24, 'DP-40 Hero of the Federation', 'Though originally intended solely for ceremonial use, its inspirational energy proved equally useful on the battlefield.', 'Medium', 100, 500, 100, NULL, 'armor'),
(25, 'DP-53 Savior of the Free', 'A faithful replica of the armor worn at The Battle of Liberty Peak. Honor their legacy, and wear it with pride.', 'Medium', 100, 500, 100, NULL, 'armor'),
(26, 'EX-00 Prototype X', 'The end result of several billion Super Credits and 12 years of research into creating “the Solider of Tomorrow”.', 'Light', 50, 550, 125, NULL, 'armor'),
(27, 'EX-03 Prototype 3', 'Because this prototype''s wires operate at 400,000 volts, it also includes a handy rubber underlayer for insulation.', 'Medium', 100, 500, 100, NULL, 'armor'),
(34, 'FS-34 Exterminator', 'Features a patented non-stick coating, which makes scraping viscera off after a long day of battle less taxing.', 'Medium', 100, 500, 100, NULL, 'armor'),
(35, 'FS-37 Ravager', 'Contains many small pockets, allowing the user to evenly distribute the weight of ammunition, samples, and cool rocks.', 'Light', 50, 550, 125, NULL, 'armor'),
(36, 'FS-38 Eradicator', 'First deployed in the mines of Cyberstan, where it offered protection against explosions in the hydrogen-rich caverns.', 'Light', 50, 550, 125, NULL, 'armor'),
(37, 'FS-55 Devastator', 'Contains many small pockets, allowing the user to evenly distribute the weight of ammunition, samples, and cool rocks.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(38, 'FS-61 Dreadnought', 'With genuine gold accents, 74% of colonists voted this armor the set they would most like to be buried in.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(39, 'SA-04 Combat Technician', 'Due to the enhanced strength caused by this armor, caution is advised when using door handles or embracing colleagues.', 'Medium', 100, 500, 100, NULL, 'armor'),
(40, 'SA-12 Servo Assisted', 'Each servo-assisted limb contains 138 miniature motors, to support a natural gait and long-term spinal health.', 'Medium', 100, 500, 100, NULL, 'armor'),
(41, 'SA-12 Servo-Assisted', 'Each servo-assisted limb contains 138 miniature motors, to support a natural gait and long-term spinal health.', 'Medium', 100, 500, 100, NULL, 'armor'),
(42, 'SA-25 Steel Trooper', 'For optimal performance, the manufacturer recommends avoiding immersing this armor in salt water for prolonged periods.', 'Medium', 100, 500, 100, NULL, 'armor'),
(43, 'SA-32 Dynamo', 'In mountainous colonies, domestic variants of this armor are used to throw weather monitoring equipment uphill.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(44, 'SC-15 Drone Master', 'Some soldiers report picking up strange radio interference when wearing this armor near alien artifacts.', 'Medium', 100, 500, 100, NULL, 'armor'),
(45, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Light', 50, 550, 125, NULL, 'armor'),
(46, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Light', 70, 530, 115, NULL, 'armor'),
(47, 'SC-37 Legionnaire', 'This armor is based on the antique uniforms of the ''Super Earth Legion'', a less patriotic precursor to the Helldivers.', 'Light', 50, 550, 125, NULL, 'armor'),
(48, 'TR-117 Alpha Commander', 'For warriors who are so strong and confident that they don''t need any reassurance whatsoever.', 'Medium', 100, 500, 100, NULL, 'armor'),
(49, 'TR-40 Gold Eagle', 'This high-visibility armor allows it''s bearer to be easily seen through smoke, fog, and spewing viscera.', 'Heavy', 150, 500, 100, NULL, 'armor'),
(50, 'TR-62 Knight', 'Crafted to deliver Justice to the darkest crevices of the galaxy.', 'Medium', 100, 450, 50, NULL, 'armor'),
(51, 'TR-7 Ambassador of the Brand', 'Promotional armor made by SUMY Corp. as part of a highly successful marketing campaign for frozen yogurt.', 'Medium', 100, 500, 100, NULL, 'armor'),
(52, 'TR-9 Cavalier of Democracy', 'Bearers of this armor ride no equine mount, but are nonetheless borne to battle atop the trusty steed of Liberty.', 'Medium', 100, 500, 100, NULL, 'armor'),
(53, 'PH-202 Twigsnapper', 'The omission of upper-limb coverings allows for optimized freedom of movement, perspiration, and communication of upper body strength to squadmates.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(54, 'PH-9 Predator', 'Based on the uniform of Jackle 6, a veteran of the Viper Commandos who held off an entire Terminid brood on Nublaria in the First Galactic War with nothing but a machine gun, pocket knife, and Orbital Laser Strikes.', 'Light', 50, 550, 125, NULL, 'armor'),
(55, 'I-44 Salamander', 'The signature orange pauldron allows easy battlefield detection of the bearer, alive or dead, on ash-strewn battlefields.', 'Heavy', 150, 450, 50, NULL, 'armor'),
(62, 'UF-16 Inspector', 'Made famous by the "Truth Enforcers: Enforcers of Truth" mystery novels, this armor calls to mind those paragons of patriotism who protect us from treasonous lies.', 'Medium', 100, 500, 100, NULL, 'armor'),
(56, 'I-92 Fire Fighter', 'The heavy rubber tunic and reflective limb guards, originally designed to save citizens from burning buildings, now enable the liberal application of the cleansing fires of Justice.', 'Medium', 100, 500, 100, NULL, 'armor'),
(57, 'I-09 Heatseeker', 'The burnished blood-red plates are forged in righteous fire, like the heroes they were wrought to protect.', 'Light', 50, 550, 125, NULL, 'armor'),
(58, 'I-102 Draconaught', 'Completely sheathed in 14-cm silica fiber foam, except for a thin tube to the ear canal to enable hearing the satisfying screeches of Freedom''s enemies as they burn.', 'Medium', 100, 500, 100, NULL, 'armor'),
(59, 'AF-50 Noxious Ranger', 'We fear not poison, fear not death; spite our foes with every breath.” From the beloved classic Hazard Pay: The Musical.', 'Medium', 50, 550, 125, NULL, 'armor'),
(60, 'AF-02 Haz-Master', 'Developed by the Ministry of Science while investigating the phenomenon known as The Gloom, this armor is non-permeable and squeak resistant.', 'Medium', 100, 500, 100, NULL, 'armor'),
(61, 'UF-50 Bloodhound', 'Users are advised not to scratch at the lacquer, as the Red 20,000 pigment that gives this armor its signature sheen may be correlated with rapid DNA unspooling.', 'Medium', 100, 500, 100, NULL, 'armor'),
(63, 'UF-84 Doubt Killer', 'Developed by the Ministry of Science while investigating the phenomenon known as The Gloom, this armor is non-permeable and squeak resistant.', 'Medium', 100, 500, 100, NULL, 'armor'),
(64, 'DP-00 Tactical', 'This classic armour set is recognised by every citizen: worn by the heroic Helldivers who battled and forever defeated the Terminids, Cyborgs, and the Illuminate in the First Galactic War', 'Medium', 100, 500, 100, NULL, 'armor'),
(65, 'PH-56 Jaguar', '', 'Medium', 100, 500, 100, NULL, 'armor'),
(66, 'CE-101 Guerilla Gorilla', '', 'Heavy', 150, 450, 50, NULL, 'armor');

INSERT INTO public.gear_has_passives VALUES (1, 4),
(1, 7), (2, 7),
(3, 11), (3, 2),
(4, 7), (5, 8),
(6, 8), (7, 8),
(8, 8), (9, 8),
(10, 8), (11, 8),
(12, 2), (13, 2),
(14, 8), (15, 2),
(16, 2), (17, 2),
(18, 11), (19, 7),
(19, 6), (21, 3),
(22, 7), (23, 9),
(24, 9), (25, 9),
(26, 12), (26, 8),
(27, 12), (28, 12),
(29, 11), (31, 11),
(32, 11), (34, 11),
(35, 11), (36, 11),
(37, 11), (38, 6),
(39, 3), (40, 6),
(41, 6), (42, 6),
(43, 6), (44, 8),
(45, 3), (46, 3),
(47, 6), (48, 2),
(49, 7), (50, 6),
(51, 7), (52, 9),
(53, 5), (54, 5),
(55, 10), (56, 10),
(57, 10), (58, 10),
(59, 1), (60, 1),
(61, 13), (62, 13),
(63, 13), (64, 9),
(65, 5), (66, 8);

INSERT INTO public.gear VALUES (67,'Agent of Oblivion', '0.05% of profits are donated to Superstone National Park as part of the Ministry of Unity''s ''Greener Galaxy'' campaign.', 'Medium', 100, 100, 100, 'images/7993acf3-e6e4-455c-b91d-f65bdca3dbdf.png'),
(68,'Bastion of Integrity', 'A black, red and white cape with some type of war insignia enscribed on the back.', 'Medium', 100, 100, 100, NULL, 'cape'),
(69,'Beacon of Mercy', 'The clasps on this cape are made from melted down Automaton housings—evidence of Democracy''s inevitable triumph.', 'Medium', 100, 100, 100, NULL, 'cape'),
(70,'Blazing Samaritan', 'A white and green cape with red accents. Some type of war insignia is centered on the back.', 'Medium', 100, 100, 100, NULL, 'cape'),
(71,'Botslayer', 'A cape that strikes a subroutine emulating fear into the CPUs of all Automatons who conduct visual scans of it.', 'Medium', 100, 100, 100, NULL, 'cape'),
(72,'Cloak of Posterity''s Gratitude', 'A representation of the thankfullness of those infinite descendants whose liberated existence we strive to ensure.', 'Medium', 100, 100, 100, NULL, 'cape'),
(73,'Cresting Honor', 'An entirely olive-green cape with minimal markings or insignia.', 'Medium', 100, 100, 100, NULL, 'cape'),
(74,'Dissident''s Nightmare', 'After extensive testing in PAtriotic Rehabilitation Centers, this design was proved most terrifying to dissent-afflicted individuals.', 'Medium', 100, 100, 100, NULL, 'cape'),
(75,'Drape of Glory', 'Research suggests that Helldivers wearing this cape are seen as 17% more patriotic.', 'Medium', 100, 100, 100, NULL, 'cape'),
(76, 'Drape of Glory', 'Research suggests that Helldivers wearing this cape are seen as 17% more patriotic.', 'Medium', 100, 100, 100, NULL, 'cape'),
(77, 'Eagle''s Fury', 'One of the earliest to be mass-produced, this cape has been the final sight of untold numbers of Freedom''s foes.', 'Medium', 100, 100, 100, NULL, 'cape'),
(78, 'Foesmasher', 'Durable, waterproof, and thermally-lined, surplus units of this cape are favored by domestic campers, to make tents.', 'Medium', 100, 100, 100, NULL, 'cape'),
(79, 'Freedom''s Tapestry', 'Let all who see this cape be struck still with Freedom''s beauty, or struck dead with Liberty''s bullets.', 'Medium', 100, 100, 100, NULL, 'cape'),
(80, 'Harbinger of True Equality', 'Wearers of this cape know that even enemies of Freedom deserve to be equal. Equally dead.', 'Medium', 100, 100, 100, NULL, 'cape'),
(81, 'Independence Bringer', 'This cape''s cropped length symbolizes the brevity of galactic conflicts, thanks to the efficiency of the Helldivers.', 'Medium', 100, 100, 100, NULL, 'cape'),
(82, 'Judgement Day', 'The Helldiver Skull is said to strike fear in the hearts of foes attempting to sneak up on those wearing this cape.', 'Medium', 100, 100, 100, NULL, 'cape'),
(83, 'Justice for All', 'Bearers of this cape take upon a sacred duty: that of delivering righteous retribution to every last deserving being.', 'Medium', 100, 100, 100, NULL, 'cape'),
(84, 'Liberty''s Herald', 'The two stripes server as a reminder of the two pillars of successful military campaigns: attack, and further attack.', 'Medium', 100, 100, 100, NULL, 'cape'),
(85, 'Light of Eternal Liberty', 'A black and white cape with golden accents and geometric shape work. A hypnotizing diamond in the center spreads Democracy far and wide.', 'Medium', 100, 100, 100, NULL, 'cape'),
(86, 'Light of Eternal Liberty', 'The unimpeachable justice of this cape''s design is said to blind the enemies of Freedom with its glorious light.', 'Medium', 100, 100, 100, NULL, 'cape'),
(87, 'Mantle of True Citizenship', 'The featherlight construction belies the heavy burden this cape entails - to live the Creed of the True Citizen', 'Medium', 100, 100, 100, NULL, 'cape'),
(88, 'Martyris Rex', 'It is said that only the truly Democratic can lift this cape to their shoulders.', 'Medium', 100, 100, 100, NULL, 'cape'),
(89, 'Order of the Venerated Ballot', 'Adorned with the insignia of the Order of the Venerated Ballot, a Ministry-sanctioned Patriot''s Club for citizens who pledge themselves to preserving the sanctity of voting.', 'Medium', 100, 100, 100, NULL, 'cape'),
(90, 'Pinions of Everlasting Glory', 'All but ensures ascension to the immortal ranks of those enshrined in the Super Earth Digital Archive of Valorous Acts', 'Medium', 100, 100, 100, NULL, 'cape'),
(91, 'The Cape of Stars and Suffrage', 'A symbol of Super Earth''s Astral Promise: that every star shall one day illuminate throngs of joyous voters.', 'Medium', 100, 100, 100, NULL, 'cape'),
(92, 'Tideturner', 'Some say that a mere glimpse of this cape, fluttering majestically in the breeze, is enough to spur a squad to victory.', 'Medium', 100, 100, 100, NULL, 'cape'),
(93, 'Tyrant Hunter', 'The cape''s shredded hem presages the unrelenting savagery its wielder will visit upon the nemeses of Freedom.', 'Medium', 100, 100, 100, NULL, 'cape'),
(94, 'Unblemished Allegiance', 'A choir of patriotic schoolchildren sings the Super Earth anthem to each cape as the final step in its production.', 'Medium', 100, 100, 100, NULL, 'cape'),
(95, 'Unblemished Allegiance', 'A choir of patriotic schoolchildren sings the Super Earth anthem to each cape as the final step in its production.', 'Medium', 100, 100, 100, NULL, 'cape'),
(96, 'Will of the People', 'Contains a grain of sand from Super Earth—so its bearers carry a small piece of Liberty with them, wherever they go.', 'Medium', 100, 100, 100, NULL, 'cape'),
(97, 'Wings of Valor', 'Based on the ceremonial pennant flags of early Super Earth, which now adorn the entrance to each Ministry.', 'Medium', 100, 100, 100, NULL, 'cape'),
(98, 'Fallen Hero’s Vengeance', 'Our heroic fallen live on in this cape, guiding its bearer''s aim to the heart of those who killed them.', 'Medium', 100, 100, 100, NULL, 'cape'),
(99, 'Mark of the Crimson Fang', 'Marks the most obedient of the obedient, those who will strike headlong at the veins of Tyranny and administer the sweet antidote of Freedom.', 'Medium', 100, 100, 100, NULL, 'cape'),
(100, 'Executioner''s Canopy', 'Crests the shoulders of those who deliver the final—and most indispensable—stroke of Justice.', 'Medium', 100, 100, 100, NULL, 'cape'),
(101, 'Purifying Eclipse', 'A tribute to the liberation of Choepessa IV in the First Galactic War, in which so much ordnance was detonated that its sun was occluded by ash for an entire lunar cycle.', 'Medium', 100, 100, 100, NULL, 'cape'),
(102, 'The Breach', 'As documented in the bestselling graphic novel “The Breach,” the final mission of the 361st “Freedom''s Flame” saw the storied unit deploy straight into the heart of a Supervolcano, sacrificing themselves to trigger an eruption and wipe out a massive Terminid swarm.', 'Medium', 100, 100, 100, NULL, 'cape'),
(103, 'Standard of Safe Distance', '', 'Medium', 100, 100, 100, NULL, 'cape'),
(104, 'Patient Zero''s Rememberance', '', 'Medium', 100, 100, 100, NULL, 'cape'),
(105, 'Pride of the Whistleblower', 'Granted to the Truth Enforcers'' Informant of the Month, this tasteful cape conjures images of dissident blood on asphalt.', 'Medium', 100, 100, 100, NULL, 'cape'),
(106, 'Proof of Faultless Virtue', 'This cape signifies that its wearer thinks, feels, and acts correctly at all times, and thus bears the responsibility to educate and re-educate their fellow citizen.', 'Medium', 100, 100, 100, NULL, 'cape'),
(107, 'Cover of Darkness', 'When children have trouble sleeping, tucking them in under this cape reminds them that they are never alone, for Liberty''s unseen defenders are always watching over them.', 'Medium', 100, 100, 100, NULL, 'cape');

INSERT INTO public.gear_has_passives VALUES (67,4),
(68,4), (69,4),
(70,4), (71,4),
(72,4), (73,4),
(74,4), (75,4),
(76, 4), (77, 4),
(78, 4), (79, 4),
(80, 4), (81, 4),
(82, 4), (83, 4),
(84, 4), (85, 4),
(86, 4), (87, 4),
(88, 4), (89, 4),
(90, 4), (91, 4),
(92, 4), (93, 4),
(94, 4), (95, 4),
(96, 4), (97, 4),
(98, 4), (99, 4),
(100, 4), (101, 4),
(102, 4), (103, 4),
(104, 4), (105, 4),
(106, 4), (107, 4);

INSERT INTO public.gear VALUES (108,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(109,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(110,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(111,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(112,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(113,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(114,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(115,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(116,'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(117, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(118, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(119, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(120, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(121, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(122, 'B-01 Tactical', 'This armor is the Super Earth Standard Issue, made from the same titanium alloy as the Destroyer''s hull.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(123, 'B-08 Light Gunner', 'Compact and flexible, this kevlar armor adds minimal mass, making it a common choice for Helldiver fitness tests.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(124, 'B-24 Enforcer', 'In field tests, 84% of users said that the armor improved their posture and self-esteem.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(125, 'B-27 Fortified Commando', 'This armor set first appeared in the music video for the summer anthem ''Our Love is Like Liberty (Indestructible)''.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(126, 'CE-07 Demolition Specialist', 'Originally worn by lunar terraformers, this suit can withstand rapid changes in pressure, heat, and personal velocity.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(127, 'CE-27 Ground Breaker', '''The ground is just another obstacle that hasn''t yet been cleared.'' - SGM Janet Jones, Excavation Corps Founder.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(128, 'CE-35 Trench Engineer', 'After colonists of Hellmire recovered a lost shipment of this armor, the local pastime of fence-smashing was born.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(129, 'CE-35 Trench Engineer', 'After colonists of Hellmire recovered a lost shipment of this armor, the local pastime of fence-smashing was born.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(130, 'CE-64 Grenadier', 'The set''s classic advertising campaign ''Have you tried a grenade?'' has remained unchanged for over 70 years', 'Medium', 100, 100, 100, NULL, 'helmet'),
(131, 'CE-67 Titan', 'A quality product, this armor can destroy over 300,000 kilometers of fencing with no decline in operational efficiency.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(132, 'CE-74 Breaker', 'A domestic version of this armor is available for citizens who wish to perform efficient home renovation projects.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(133, 'CE-81 Juggernaut', 'One of the most durable engineer armors available, each set is quality tested by an impact with a full-grown Charger.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(134, 'CM-06 Combat Medic', 'This armor was designed by PFC Rodney A. Carmichael, the first Helldiver to use a stim on an ally instead of himself.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(135, 'CM-09 Bonesnapper', 'Based on a colonial surgeon''s gown, where surgeries were often interrupted by a need to perform defensive duties', 'Medium', 100, 100, 100, NULL, 'helmet'),
(136, 'CM-09 Bonesnapper', 'Based on a colonial surgeon''s gown, where surgeries were often interrupted by a need to perform defensive duties.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(137, 'CM-10 Clinician', 'Featuring patented reverse-seam technology, to reduce the likelihood of bodily fluids entering the armor''s interior.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(138, 'CM-14 Physician', 'The distinctive red, white, and green of the Intergalactic Medical Corps signal to all Helldivers that help is at hand.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(139, 'CM-14 Physician', 'The distinctive red, white, and green of the Intergalactic Medical Corps signal to all Helldivers that help is at hand.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(140, 'CM-17 Butcher', 'An armor often worn by frontline surgeons, who are skilled at both putting bodies back together and taking them apart.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(141, 'CM-21 Trench Paramedic', 'The suit was once designed to hold a variety of battlefield medical equipment. Now it holds a generous supply of stims.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(142, 'CW-22 Kodiak', 'The CW-22 Kodiak armor was thoroughly pressure-tested by patriotic volunteers, as part of the ''Test Subjects for Super-Earth'' Citizen Advancement Program.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(143, 'CW-36 Winter Warrior', 'Offering camouflage in snowy environments, surplus sets of this armor are used by nature photographers and keen hunters alike.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(144, 'CW-36 Winter Warrior', 'Offering camouflage in snowy environments, surplus sets of this armor are used by nature photographers and keen hunters alike.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(145, 'CW-4 Arctic Ranger', 'Features a utility belt with pockets that can be filled with any number of things, such as pocket knives, mementos from home, and interesting rocks.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(146, 'CW-9 White Wolf', 'The pattern used for this armor is the result of the Winter Camouflage Improvement Effort, which considered 136 entrants before determining the color white would best blend in with snow.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(147, 'DP-11 Champion of the People', 'The three stripes on the pauldrons stand for the three principles of Super Earth: Liberty, Democracy, and Prosperity.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(148, 'DP-11 Champion of the People', 'The three stripes on the pauldrons stand for the three principles of Super Earth: Liberty, Democracy, and Prosperity.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(149, 'DP-40 Hero of the Federation', 'Though originally intended solely for ceremonial use, its inspirational energy proved equally useful on the battlefield.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(150, 'DP-40 Hero of the Federation', 'Though originally intended solely for ceremonial use, its inspirational energy proved equally useful on the battlefield.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(151, 'DP-53 Savior of the Free', 'A faithful replica of the armor worn at The Battle of Liberty Peak. Honor their legacy, and wear it with pride.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(152, 'EX-00 Prototype X', 'The end result of several billion Super Credits and 12 years of research into creating “the Solider of Tomorrow”.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(153, 'EX-00 Prototype X', 'The end result of several billion Super Credits and 12 years of reseach into creating ''the Soldier of Tomorrow.''', 'Medium', 100, 100, 100, NULL, 'helmet'),
(154, 'EX-03 Prototype 3', 'Because this prototype’s wires operate at 400,000 volts, it also includes a handy rubber underlayer for insulation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(155, 'EX-03 Prototype 3', 'Because this prototype''s wires operate at 400,000 volts, it also includes a handy rubber underlayer for insulation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(156, 'EX-16 Prototype 16', 'As the electric arc generates a strong magnetic field, wearers should avoid use while in vicinity of stapled paperwork.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(157, 'EX-16 Prototype 16', 'As the electric arc generates a strong magnetic field, wearers should avoid use while in the vicinity of stapled paperwork', 'Medium', 100, 100, 100, NULL, 'helmet'),
(158, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(159, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(160, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(161, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(162, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(163, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(164, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes', 'Medium', 100, 100, 100, NULL, 'helmet'),
(165, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(166, 'FS-05 Marksman', 'While early prototypes used shock-absorbing gels, this armor stabilizes aim with the use of internal gyroscopes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(167, 'FS-11 Executioner', 'Popularized by actor Chip Messiter, who wore this in the action-rom-com-musical ''Lost My Heart to a Man in a Helmet.''', 'Medium', 100, 100, 100, NULL, 'helmet'),
(168, 'FS-23 Battle Master', 'This aim-stabilizing armor found surprising secondary market success among alien birdwatching enthusiasts.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(169, 'FS-23 Battle Master', 'This aim-stabilizing armor found surprising secondary market success among alien birdwatching enthusiasts.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(170, 'FS-34 Exterminator', 'Features a patented non-stick coating, which makes scraping viscera off after a long day of battle less taxing.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(171, 'FS-37 Ravager', 'Contains many small pockets, allowing the user to evenly distribute the weight of ammunition, samples, and cool rocks.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(172, 'FS-38 Eradicator', 'First deployed in the mines of Cyberstan, where it offered protection against explosions in the hydrogen-rich caverns.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(173, 'FS-55 Devastator', 'Domestic versions of this armor enable colonial farmers to plant crops and mines side by side, safely.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(174, 'FS-61 Dreadnought', 'With genuine gold accents, 74% of colonists voted this armor the set they would most like to be buried in.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(175, 'SA-04 Combat Technician', 'Due to the enhanced strength caused by this armor, caution is advised when using door handles or embracing colleagues.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(176, 'SA-04 Combat Technician', 'Due to the enhanced strength caused by this armor, caution is advised when using door handles or embracing colleagues.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(177, 'SA-12 Servo Assisted', 'Each servo-assisted limb contains 138 miniature motors, to support a natural gait and long-term spinal health.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(178, 'SA-12 Servo-Assisted', 'Each servo-assisted limb contains 138 miniature motors, to support a natural gait and long-term spinal health.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(179, 'SA-25 Steel Trooper', 'For optimal performance, the manufacturer recommends avoiding immersing this armor in salt water for prolonged periods.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(180, 'SA-25 Steel Trooper', 'For optimal performance, the manufacturer recommends avoiding immersing this armor in salt water for prolonged periods.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(181, 'SA-32 Dynamo', 'In mountainous colonies, domestic variants of this armor are used to throw weather monitoring equipment uphill.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(182, 'SA-32 Dynamo', 'In mountainous colonies, domestic variants of this armor are used to throw weather monitoring equipment uphill.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(183, 'SC-15 Drone Master', 'Some soldiers report picking up strange radio interference when wearing this armor near alien artifacts.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(184, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(185, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(186, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(187, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(188, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(189, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(190, 'SC-30 Trailblazer Scout', 'The patented fabric absorbs visible, infrared, and ultraviolet radiation, to prevent detection by all known species.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(191, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(192, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(193, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(194, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(195, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(196, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(197, 'SC-34 Infiltrator', 'This suit''s plutonium-238 nuclear battery enables environmental scanning long after the user has ceased operation.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(198, 'SC-37 Legionnaire', 'This armor is based on the antique uniforms of the ''Super Earth Legion'', a less patriotic precursor to the Helldivers.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(199, 'TR-117 Alpha Commander', 'For warriors who are so strong and confident that they don''t need any reassurance whatsoever.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(200, 'TR-40 Gold Eagle', 'This high-visibility armor allows it''s bearer to be easily seen through smoke, fog, and spewing viscera.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(201, 'TR-62 Knight', 'Crafted to deliver Justice to the darkest crevices of the galaxy.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(202, 'TR-7 Ambassador of the Brand', 'Promotional armor made by SUMY Corp. as part of a highly successful marketing campaign for frozen yogurt.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(203, 'TR-9 Cavalier of Democracy', 'Bearers of this armor ride no equine mount, but are nonetheless borne to battle atop the trusty steed of Liberty.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(204, 'PH-202 Twigsnapper', 'The omission of upper-limb coverings allows for optimized freedom of movement, perspiration, and communication of upper body strength to squadmates.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(205, 'PH-9 Predator', 'Based on the uniform of Jackle 6, a veteran of the Viper Commandos who held off an entire Terminid brood on Nublaria in the First Galactic War with nothing but a machine gun, pocket knife, and Orbital Laser Strikes.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(206, 'I-44 Salamander', 'The signature orange pauldron allows easy battlefield detection of the bearer, alive or dead, on ash-strewn battlefields.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(207, 'I-92 Fire Fighter', 'The heavy rubber tunic and reflective limb guards, originally designed to save citizens from burning buildings, now enable the liberal application of the cleansing fires of Justice.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(208, 'I-09 Heatseeker', 'The burnished blood-red plates are forged in righteous fire, like the heroes they were wrought to protect.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(209, 'I-102 Draconaught', 'Completely sheathed in 14-cm silica fiber foam, except for a thin tube to the ear canal to enable hearing the satisfying screeches of Freedom''s enemies as they burn.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(210, 'AF-50 Noxious Ranger', 'We fear not poison, fear not death; spite our foes with every breath.” From the beloved classic Hazard Pay: The Musical.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(211, 'AF-02 Haz-Master', 'Developed by the Ministry of Science while investigating the phenomenon known as The Gloom, this armor is non-permeable and squeak resistant.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(212, 'UF-50 Bloodhound', 'Users are advised not to scratch at the lacquer, as the Red 20,000 pigment that gives this armor its signature sheen may be correlated with rapid DNA unspooling.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(213, 'UF-16 Inspector', 'Made famous by the "Truth Enforcers: Enforcers of Truth" mystery novels, this armor calls to mind those paragons of patriotism who protect us from treasonous lies.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(214, 'UF-84 Doubt Killer', 'Developed by the Ministry of Science while investigating the phenomenon known as The Gloom, this armor is non-permeable and squeak resistant.', 'Medium', 100, 100, 100, NULL, 'helmet'),
(215, 'DP-00 Tactical', 'This classic armour set is recognised by every citizen: worn by the heroic Helldivers who battled and forever defeated the Terminids, Cyborgs, and the Illuminate in the First Galactic War', 'Medium', 100, 100, 100, NULL, 'helmet'),
(216, 'PH-56 Jaguar', '', 'Medium', 100, 100, 100, NULL, 'helmet'),
(217, 'CE-101 Guerilla Gorilla', '', 'Medium', 100, 100, 100, NULL, 'helmet');



INSERT INTO public.gear_has_passives VALUES (108, 4),
(109, 4), (110, 4),
(111, 4), (112, 4),
(113, 4), (114, 4),
(115, 4), (116, 4),
(117, 4), (118, 4),
(119, 4), (120, 4),
(121, 4), (122, 4),
(123, 4), (124, 4),
(125, 4), (126, 4),
(127, 4), (128, 4),
(129, 4), (130, 4),
(131, 4), (132, 4),
(133, 4), (134, 4),
(135, 4), (136, 4),
(137, 4), (138, 4),
(139, 4), (140, 4),
(141, 4), (142, 4),
(143, 4), (144, 4),
(145, 4), (146, 4),
(147, 4), (148, 4),
(149, 4), (150, 4),
(151, 4), (152, 4),
(153, 4), (154, 4),
(155, 4), (156, 4),
(157, 4), (158, 4),
(159, 4), (160, 4),
(161, 4), (162, 4),
(163, 4), (164, 4),
(165, 4), (166, 4),
(167, 4), (168, 4),
(169, 4), (170, 4),
(171, 4), (172, 4),
(173, 4), (174, 4),
(175, 4), (176, 4),
(177, 4), (178, 4),
(179, 4), (180, 4),
(181, 4), (182, 4),
(183, 4), (184, 4),
(185, 4), (186, 4),
(187, 4), (188, 4),
(189, 4), (190, 4),
(191, 4), (192, 4),
(193, 4), (194, 4),
(195, 4), (196, 4),
(197, 4), (198, 4),
(199, 4), (200, 4),
(201, 4), (202, 4),
(203, 4), (204, 4),
(205, 4), (206, 4),
(207, 4), (208, 4),
(209, 4), (210, 4),
(211, 4), (212, 4),
(213, 4), (214, 4),
(215, 4), (216, 4),
(217, 4);

INSERT INTO public.weapon VALUES
(1, 'AR-23 Liberator', 'The SEAF standard assault rifle, balancing power, fire rate, and weight for a reliable weapon against smaller targets.', 'Assault Rifle', 70, 45, 14, 640, NULL, 'primary', 'Light'),
(2, 'AR-23P Liberator Penetrator', 'A modified Liberator featuring a scope and firing armor-piercing rounds, to help users take down armored targets.', 'Assault Rifle', 60, 45, 18, 640, NULL, 'primary', 'Light'),
(3, 'AR-23C Liberator Concussive', 'A modified Liberator featuring explosive rounds and a red-dot sight. Trades increased damage for increased recoil.', 'Assault Rifle', 65, 30, 28, 320, NULL, 'primary', 'Light'),
(4, 'SG-8 Punisher', 'A powerful dual magazine pump-action shotgun, with limited armor penetration. Ideal for small and fast targets.', 'Shotgun', 405, 16, 120, 80, NULL, 'primary', 'Light'),
(5, 'SG-8P Punisher Plasma', 'A modified Punisher shotgun firing exploding plasma rounds. Fire carefully - exploding plasma can injure squadmates.', 'Energy-based', 250, 8, 35, 100, NULL, 'primary', 'Light'),
(6, 'SG-8S Slugger', 'A modified Punisher shotgun firing heavy, high-damage slug rounds. Perfect for punching holes in big targets.', 'Shotgun', 250, 16, 120, 80, NULL, 'primary', 'Light'),
(7, 'SG-225 Breaker', 'A fully-automatic shotgun with a high rate of fire, excellent for controlling crowds. Requires frequent reloading.', 'Shotgun', 330, 16, 55, 300, NULL, 'primary', 'Light'),
(8, 'SG-225IE Breaker Incendiary', 'A modified Breaker shotgun firing incendiary projectiles. Generates heat during use, so limited to burst fire.', 'Shotgun', 240, 25, 41, 300, NULL, 'primary', 'Light'),
(9, 'SG-225SP Breaker Spray&Pray', 'A modified Breaker shotgun firing birdshot, small pellets which saturate an area to clear up smaller targets.', 'Shotgun', 240, 26, 45, 330, NULL, 'primary', 'Light'),
(10, 'ARC-12 Blitzer', 'This shotgun blasts a wide burst of high-voltage electricity that arcs between all units - enemy or otherwise - within range.', 'Energy-based', 250, 999, 60, 45, NULL, 'primary', 'Light'),
(11, 'MP-98 Knight', 'A submachine gun with an extremely high rate of fire, which can be operated with one hand. Ideal for multitasking.', 'SMG', 65, 50, 15, 1380, NULL, 'primary', 'Light'),
(12, 'SMG-37 Defender', 'A high-caliber submachine gun which can be fired with one hand. Has a relatively low rate of fire.', 'SMG', 75, 45, 10, 520, NULL, 'primary', 'Light'),
(13, 'R-63 Diligence', 'This high-caliber marksman rifle trades magazine capacity and rate of fire for powerful, accurate shots.', 'Marksman Rifle', 165, 20, 35, 350, NULL, 'primary', 'Light'),
(14, 'R-63CS Diligence Counter Sniper', 'A modified Diligence rifle offering increased damage, but a reduced rate of fire. Fires a single bullet at a time.', 'Marksman Rifle', 200, 15, 53, 350, NULL, 'primary', 'Light'),
(15, 'LAS-5 Scythe', 'A laser rifle firing a continuous beam. Does not need reloading, but if it overheats a new heat sink must be fitted.', 'Energy-based', 350, 8, 0, 0, NULL, 'primary', 'Light'),
(16, 'LAS-16 Sickle', 'A laser rifle, firing in short bursts. Does not need reloading, but if it overheats a new heat sink must be fitted.', 'Energy-based', 55, 7, 2, 750, NULL, 'primary', 'Light'),
(17, 'PLAS-1 Scorcher', 'A plasma rifle, firing a bolt of superheated gas which explodes on impact. Avoid standing in proximity to the blast.', 'Energy-based', 200, 20, 20, 350, NULL, 'primary', 'Light'),
(18, 'JAR-5 Dominator', 'Firing jet-propelled rounds, the Dominator trades fire rate and magazine capacity for increased damage per projectile.', 'Special', 275, 15, 75, 250, NULL, 'primary', 'Light'),
(19, 'BR-14 Adjudicator', 'An accurate, armor-penetrating rifle, the BR-14 Adjudicator delivers righteous judgement to medium-sized enemies, though its restrictive magazine limits its effectiveness against large groups.', 'Assault Rifle', 90, 30, 38, 550, NULL, 'primary', 'Light'),
(20, 'R-36 Eruptor', 'This bolt-action rifle fires jet-assisted shells that explode shrapnel in all directions upon impact. Not recommended for close-quarters use.', 'Explosive', 455, 5, 75, 25, NULL, 'primary', 'Light'),
(21, 'CB-9 Exploding Crossbow', 'Fires powerful exploding bolts that do maximum damage upon direct impact. Gravity must be accounted for when aiming.', 'Explosive', 620, 5, 35, 50, NULL, 'primary', 'Light'),
(22, 'AR-61 Tenderizer', 'A high-caliber assault rifle with a restrictive magazine size but more stopping power.', 'Assault Rifle', 95, 35, 10, 600, NULL, 'primary', 'Light'),
(23, 'SMG-72 Pummeler', 'Fires concussive rounds that stagger enemies. Slower rate of fire than other SMGs.', 'SMG', 65, 45, 10, 475, NULL, 'primary', 'Light'),
(24, 'PLAS-101 Purifier', 'A plasma rifle firing a bolt of superheated gas which explodes on impact. Each shot needs to be charged up fully before it can be fired.', 'Energy-based', 500, 15, 20, 1000, NULL, 'primary', 'Light'),
(25, 'AR-23A Liberator Carbine', 'A compact version of the Liberator designed for increased viability in close quarters. Has an increased fire rate at the cost of higher spread.', 'Assault Rifle', 70, 45, 25, 920, NULL, 'primary', 'Light'),
(26, 'SG-451 Cookout', 'A pump shotgun that fires a burst of incendiary phosphorus pellets, setting targets ablaze.', 'Shotgun', 320, 16, 100, 80, NULL, 'primary', 'Light'),
(27, 'FLAM-66 Torcher', 'A lightweight flamethrower. Shoots pressurized fuel through a dispersion nozzle into an open flame', 'Special', 375, 80, 2, 0, NULL, 'primary', 'Light'),
(28, 'SG-20 Halt', 'A humane compliance weapon with two seperate magazines: one for armor-penetrating flechette rounds and one for stun rounds.', 'Shotgun', 385, 16, 120, 80, NULL, 'primary', 'Light'),
(29, 'SMG-32 Reprimand', 'A heavy-duty submachine gun that fires large-caliber rounds, with a slower rate of fire to manage the high recoil. Ideal for use at close to medium range', 'SMG', 125, 25, 44, 490, NULL, 'primary', 'Light'),
(30, 'R-2124 Constitution', 'This ceremonial rifle is modeled after antique relics from pre-Democratic times. It is traditionally gifted to every citizen upon turning 16 to encourage service.', 'Marksman Rifle', 180, 5, 15, 60, NULL, 'primary', 'Light');

INSERT INTO public.weapon_has_firing_modes VALUES (1, 5),
(1, 6), (1, 4),
(2, 5), (2, 6),
(2, 4), (3, 5),
(3, 4), (4, 3),
(5, 3), (6, 5),
(7, 5), (7, 4),
(8, 5), (8, 4),
(9, 5), (9, 4),
(10, 5), (11, 5),
(11, 6), (11, 4),
(12, 5), (12, 6),
(12, 4), (13, 5),
(14, 5), (15, 4),
(16, 4), (17, 5),
(17, 4), (18, 5),
(18, 6), (19, 5),
(19, 4), (20, 5),
(21, 5), (22, 5),
(22, 6), (22, 4),
(23, 5), (23, 6),
(23, 4), (24, 5),
(25, 5), (25, 6),
(25, 4), (26, 3),
(27, 4), (28, 5),
(29, 5), (29, 6),
(29, 4), (30, 1);

INSERT INTO public.weapon_has_traits VALUES (1, 6),
(2, 1), (3, 6),
(4, 6), (4, 2),
(5, 1), (5, 5),
(6, 1), (6, 2),
(7, 6), (8, 6),
(8, 8), (9, 6),
(10, 1), (11, 6),
(11, 9), (12, 6),
(12, 9), (13, 6),
(14, 1), (15, 6),
(15, 4), (15, 11),
(16, 6), (16, 11),
(17, 1), (17, 5),
(18, 1), (19, 1),
(20, 1), (20, 5),
(21, 1), (21, 9),
(21, 5), (22, 6),
(23, 6), (23, 9),
(24, 1), (24, 5),
(24, 7), (25, 6),
(26, 6), (26, 2),
(26, 8), (27, 8),
(28, 6), (28, 1),
(28, 2), (29, 1),
(30, 1), (30, 2);

INSERT INTO public.weapon VALUES
(31, 'P-2 Peacemaker', 'The SEAF standard pistol - offering a high fire rate, generous capacity, and fast reloading.', 'Pistol', 75, 15, 23, 900, NULL, 'secondary', 'Light'),
(32, 'P-19 Redeemer', 'A fully-automatic pistol with an extremely high fire rate, allowing for efficient crowd control.', 'Pistol', 60, 31, 15, 1100, NULL, 'secondary', 'Light'),
(33, 'P-4 Senator', 'A high-damage revolver, which can be reloaded with single rounds. A heavy-hitting and reliable sidearm.', 'Pistol', 200, 6, 43, 200, NULL, 'secondary', 'Light'),
(34, 'LAS-7 Dagger', 'A laser pistol that fires a continuous beam. Does not require ammo but can overheat and need to change batteries.', 'Special', 250, 7, 0, 0, NULL, 'secondary', 'Light'),
(35, 'GP-31 Grenade Pistol', 'A pistol that fires grenades. Must be reloaded between shots.', 'Special', 650, 1, 43, 900, NULL, 'secondary', 'Light'),
(36, 'P-113 Verdict', 'The gas-operated, semiautomatic P-113 chambers the 14mm ''Rapid Deliberation,'' the largest centerfire cartridge of any magazine-fed pistol.', 'Pistol', 125, 10, 40, 450, NULL, 'secondary', 'Light'),
(37, 'SG-22 Bushwhacker', 'A triple-barreled, break-action, sawed-off shotgun. Switch firing modes to fire all three barrels at once.', 'Special', 405, 3, 170, 650, NULL, 'secondary', 'Light'),
(38, 'P-72 Crisper', 'A compact handgun-style flamethrower, able to project a jet of fire over short distances.', 'Special', 375, 30, 2, 0, NULL, 'secondary', 'Light'),
(39, 'P-11 Stim Pistol', 'Fires a ballistic dart at near-supersonic speeds, allowing the user to stim allies from a distance. Might sting.', 'Special', 0, 6, 6, 70, NULL, 'secondary', 'Light'),
(40, 'PLAS-15 Loyalist', 'A plasma pistol that charges each shot until the trigger is released. Plasma projectiles explode on impact.', 'Special', 125, 7, 8, 1000, NULL, 'secondary', 'Light');

INSERT INTO public.weapon_has_firing_modes VALUES
(31, 5), (32, 5),
(32, 4), (33, 5),
(34, 4), (35, 5),
(36, 5), (37, 5),
(37, 2), (38, 4),
(39, 5), (40, 7);

INSERT INTO public.weapon_has_traits VALUES
(31, 6), (31, 9),
(32, 6), (32, 9),
(33, 3), (33, 9),
(33, 2), (34, 6),
(34, 9), (34, 4),
(34, 11), (35, 9),
(35, 5), (36, 1),
(36, 9), (37, 6),
(37, 9), (38, 9),
(38, 8), (39, 9),
(39, 2), (39, 10),
(40, 1), (40, 9),
(40, 5), (40, 7);

INSERT INTO public.throwable VALUES
(1, 'G-12 High Explosive', 'A high explosive grenade which damages lightly armored targets. Creates high damage over a small area when detonated.', 800, 4, 7, 3.5, NULL),
(2, 'G-23 Stun', 'Temporarily stuns all targets within the effective radius.', 0, 6, 10, 1.8, NULL),
(3, 'G-16 Impact', 'A high explosive grenade which detonates on first impact.', 400, 4, 7, 0, NULL),
(4, 'G-3 Smoke', 'A ''compliance weapon'' to modify enemy behaviour. Creates a thick smoke screen to block targets'' line of sight', 0, 0, 5, 2.4, NULL),
(5, 'G-6 Frag', 'An antipersonnel fragmentation grenade. Creates damage over a large area when detonated.', 500, 3, 10, 2.4, NULL),
(6, 'G-10 Incendiary', 'An incendiary grenade designed for igniting intense fires upon detonation. Spreads burning material over a moderate area, causing burn damage.', 300, 3, 7, 2.9, NULL),
(7, 'G-123 Thermite Grenade', 'A thermite grenade designed to adhere to surfaces before burning at 2000°C. Capable of burning through some armor', 2000, 7, 3, 2.9, NULL),
(8, 'G-13 Incendiary Impact', 'Detonates on impact, covering the immediate vicinity in self-igniting white phosphorus.', 150, 3, 7, 0, NULL),
(9, 'K-2 Throwing Knife', 'Delivers silent justice to Freedom''s enemies.', 250, 3, 0, 0, NULL),
(10, 'G-4 Gas', 'A grenade that releases a cloud of toxic gas, effective at blinding and slowing both organic and inorganic enemies.', 3, 6, 7, 2.9, NULL);


